# Generated by Django 3.1.4 on 2020-12-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_auto_20201228_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default='', upload_to='posts_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default='Yes', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Post', max_length=100),
            preserve_default=False,
        ),
    ]
